name: Bash script execution

on: 
   push:
      branches: [main]

jobs: 
   run-bush-script:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run bash script
          run: |
            chmod +x myscript.sh
            OUTPUT=$(./myscript.sh 2>&1)
            MESSAGE="*Script execution:*\n\`\`\`$OUTPUT\`\`\`"
          curl -X POST --data-urlencode "payload={\"channel\": \"#bdg\", \"username\": \"webhookbot\", \"text\": \"MESSAGE\", \"icon_emoji\": \":ghost:\"}" $SLACK_WEBHOOK_URL
          env:
             SLACK_WEBHOOK_URL:  https://hooks.slack.com/services/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

