name: My Workflow

on: push

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
       - name: Checkout code
         uses: actions/checkout@v2
       - name: Run script
         run: |
             echo "Hello world!"
             echo "This is a simple bash script."
